export enum ErrorMessages {
  MSGE01 = "Os campos obrigatórios devem ser preenchidos",
  MSGE02 = "O cadastro já existe na base de dados",
  MSGE03 = "Erro interno do servidor",
  MSGE04 = "Não é possível alterar o status para inativo, pois o cadastro está em uso no momento",
  MSGE05 = "Cadastro não encontrado",
  MSGE06 = "Dados inválidos",
  MSGE07 = "Erro desconhecido",
  MSGE08 = "Campo menor que a quantidade mínima de caracteres requeridos",
  MSGE09 = "Campo excede a quantidade máxima permitida de caracteres",
  MSGE10 = "Valor do campo menor que o mínimo permitido",
  MSGE11 = "Valor do campo maior que o máximo permitido",
  MSGE12 = "Não é possível enviar sua imagem no momento, Por favor, tente novamente!",
  MSGE13 = "Erro - Por favor, envie apenas arquivos com extensões .jpg, .png e .jpeg",
  MSGE14 = "Erro - CPF inválido!",
  MSGE15 = "E-mail ou senha incorretos!",
  MSGE16 = "Não foi possível renovar sua sessão. Faça login novamente!",
  MSGE17 = "Credenciais inválidas",
  MSGE18 = "Acesso não autorizado",
  MSGE019 = "Não é possível criar um produto sem nenhuma categoria criada.",
  MSGE020 = "Barbeiro não possui disponibilidade nessa data.",
  MSGE021 = "Já existe um agendamento para o mesmo dia e horário",
}
